// <auto-generated />
using System;
using Annotate.Reviews.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Annotate.Reviews.Migrations
{
    [DbContext(typeof(ReviewsDbContext))]
    [Migration("20261008054952_BlockComments")]
    partial class BlockComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Annotate.Reviews.Domain.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("decided_at");

                    b.Property<string>("Feedback")
                        .HasMaxLength(1500000)
                        .HasColumnType("TEXT")
                        .HasColumnName("feedback");

                    b.Property<string>("RevisionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("revision_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId")
                        .IsUnique();

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("Annotate.Reviews.Domain.ReviewFence", b =>
                {
                    b.Property<string>("ReviewId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("review_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<string>("FenceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("fence_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt");

                    b.HasKey("ReviewId", "Ordinal");

                    b.HasIndex("ReviewId", "FenceId")
                        .IsUnique();

                    b.ToTable("review_decisions", (string)null);
                });

            modelBuilder.Entity("Annotate.Reviews.Domain.ReviewOption", b =>
                {
                    b.Property<string>("ReviewId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("review_id");

                    b.Property<string>("FenceId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("fence_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.HasKey("ReviewId", "FenceId", "Ordinal");

                    b.ToTable("review_options", (string)null);
                });

            modelBuilder.Entity("Annotate.Reviews.Domain.StoredAnnotation", b =>
                {
                    b.Property<string>("ReviewId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("review_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<bool?>("Accepted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accepted");

                    b.Property<string>("AnnotationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("annotation_id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("operator")
                        .HasColumnName("author");

                    b.Property<string>("BlockKey")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("block_key");

                    b.Property<int>("BlockOrdinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("block_ordinal");

                    b.Property<string>("Comment")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("EndOffset")
                        .HasColumnType("INTEGER")
                        .HasColumnName("end_offset");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Replacement")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("replacement");

                    b.Property<int>("StartOffset")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_offset");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.HasKey("ReviewId", "Ordinal");

                    b.ToTable("annotations", (string)null);
                });

            modelBuilder.Entity("Annotate.Reviews.Domain.StoredAnswer", b =>
                {
                    b.Property<string>("ReviewId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("review_id");

                    b.Property<string>("FenceId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("fence_id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("answer");

                    b.Property<bool>("IsOther")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_other");

                    b.HasKey("ReviewId", "FenceId");

                    b.ToTable("decision_answers", (string)null);
                });

            modelBuilder.Entity("Annotate.Reviews.Domain.StoredReply", b =>
                {
                    b.Property<string>("ReviewId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("review_id");

                    b.Property<string>("AnnotationId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("annotation_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ReplyId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("reply_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.HasKey("ReviewId", "AnnotationId", "Ordinal");

                    b.ToTable("annotation_replies", (string)null);
                });

            modelBuilder.Entity("Annotate.Reviews.Domain.ReviewFence", b =>
                {
                    b.HasOne("Annotate.Reviews.Domain.Review", null)
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Annotate.Reviews.Domain.ReviewOption", b =>
                {
                    b.HasOne("Annotate.Reviews.Domain.Review", null)
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Annotate.Reviews.Domain.StoredAnnotation", b =>
                {
                    b.HasOne("Annotate.Reviews.Domain.Review", null)
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Annotate.Reviews.Domain.StoredAnswer", b =>
                {
                    b.HasOne("Annotate.Reviews.Domain.Review", null)
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Annotate.Reviews.Domain.StoredReply", b =>
                {
                    b.HasOne("Annotate.Reviews.Domain.Review", null)
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
