// <auto-generated />
using System;
using Annotate.Plans.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Annotate.Plans.Migrations
{
    [DbContext(typeof(PlansDbContext))]
    [Migration("20261002124815_InitialPlans")]
    partial class InitialPlans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Annotate.Plans.Domain.Plan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("Annotate.Plans.Domain.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("FolderPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_path");

                    b.HasKey("Id");

                    b.HasIndex("FolderPath")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Annotate.Plans.Domain.Revision", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AcceptanceCriteria")
                        .HasColumnType("TEXT")
                        .HasColumnName("acceptance_criteria");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("markdown");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER")
                        .HasColumnName("number");

                    b.Property<string>("ParentRevisionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_revision_id");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("plan_id");

                    b.Property<string>("StoryUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("story_url");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("ParentRevisionId");

                    b.HasIndex("PlanId", "Number")
                        .IsUnique();

                    b.ToTable("revisions", (string)null);
                });

            modelBuilder.Entity("Annotate.Plans.Domain.Plan", b =>
                {
                    b.HasOne("Annotate.Plans.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Annotate.Plans.Domain.Revision", b =>
                {
                    b.HasOne("Annotate.Plans.Domain.Revision", null)
                        .WithMany()
                        .HasForeignKey("ParentRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annotate.Plans.Domain.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
