// <auto-generated />
using System;
using Annotate.Plans.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Annotate.Plans.Migrations
{
    [DbContext(typeof(PlansDbContext))]
    partial class PlansDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Annotate.Plans.Domain.Plan", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("SessionId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("Annotate.Plans.Domain.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("FolderPath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_path");

                    b.HasKey("Id");

                    b.HasIndex("FolderPath")
                        .IsUnique()
                        .HasFilter("archived_at IS NULL");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Annotate.Plans.Domain.Revision", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AcceptanceCriteria")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT")
                        .HasColumnName("acceptance_criteria");

                    b.Property<string>("Agent")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("agent");

                    b.Property<string>("ClientName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_name");

                    b.Property<string>("ClientVersion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasMaxLength(256000)
                        .HasColumnType("TEXT")
                        .HasColumnName("markdown");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER")
                        .HasColumnName("number");

                    b.Property<string>("ParentRevisionId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_revision_id");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("plan_id");

                    b.Property<string>("StoryUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("story_url");

                    b.Property<string>("Summary")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("ParentRevisionId");

                    b.HasIndex("PlanId", "Number")
                        .IsUnique();

                    b.ToTable("revisions", (string)null);
                });

            modelBuilder.Entity("Annotate.Plans.Domain.StoredBlock", b =>
                {
                    b.Property<string>("RevisionId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("revision_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordinal");

                    b.Property<string>("BlockKey")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("block_key");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("SectionPath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("section_path");

                    b.Property<int>("SourceEnd")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_end");

                    b.Property<int>("SourceStart")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_start");

                    b.HasKey("RevisionId", "Ordinal");

                    b.ToTable("blocks", (string)null);
                });

            modelBuilder.Entity("Annotate.Plans.Domain.Plan", b =>
                {
                    b.HasOne("Annotate.Plans.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Annotate.Plans.Domain.Revision", b =>
                {
                    b.HasOne("Annotate.Plans.Domain.Revision", null)
                        .WithMany()
                        .HasForeignKey("ParentRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Annotate.Plans.Domain.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Annotate.Plans.Domain.StoredBlock", b =>
                {
                    b.HasOne("Annotate.Plans.Domain.Revision", null)
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
